spring:
   datasource:
      username: dog_rescue
      password: dog_rescue
      url: jdbc:mysql://localhost:3306/dog_rescue

   jpa:
      hibernate:
         ddl-auto: none #this makes 
         #hibernate not to populate tables before jpa by setting to none from update#
      show-sql: true
      
   sql:
      init:
         model: always
   