INSERT INTO breed (name) VALUE ('Afghan Hound');
INSERT INTO breed (name) VALUE ('Airedale Terrier');
INSERT INTO breed (name) VALUE ('Akita');
INSERT INTO breed (name) VALUE ('Alaskan Malamute');
INSERT INTO breed (name) VALUE ('American Bulldog');
INSERT INTO breed (name) VALUE ('American Staffordshire Terrier');
INSERT INTO breed (name) VALUE ('Australian Cattle Dog');
INSERT INTO breed (name) VALUE ('Australian Shepherd');
INSERT INTO breed (name) VALUE ('Basset Hound');
INSERT INTO breed (name) VALUE ('Beagle');
INSERT INTO breed (name) VALUE ('Bernese Mountain Dog');
INSERT INTO breed (name) VALUE ('Bichon Frise');
INSERT INTO breed (name) VALUE ('Bloodhound');
INSERT INTO breed (name) VALUE ('Border Collie');
INSERT INTO breed (name) VALUE ('Boxer');
INSERT INTO breed (name) VALUE ('Bulldog');
INSERT INTO breed (name) VALUE ('Corgi');
INSERT INTO breed (name) VALUE ('Dachshund');
INSERT INTO breed (name) VALUE ('Dalmatian');
INSERT INTO breed (name) VALUE ('Doberman Pinscher');
INSERT INTO breed (name) VALUE ('English Springer Spaniel');
INSERT INTO breed (name) VALUE ('French Bulldog');
INSERT INTO breed (name) VALUE ('German Shepherd');
INSERT INTO breed (name) VALUE ('Golden Retriever');
INSERT INTO breed (name) VALUE ('Great Dane');
INSERT INTO breed (name) VALUE ('Greyhound');
INSERT INTO breed (name) VALUE ('Havanese');
INSERT INTO breed (name) VALUE ('Labrador Retriever');
INSERT INTO breed (name) VALUE ('Maltese');
INSERT INTO breed (name) VALUE ('Mastiff');
INSERT INTO breed (name) VALUE ('Papillon');
INSERT INTO breed (name) VALUE ('Poodle');
INSERT INTO breed (name) VALUE ('Pug');
INSERT INTO breed (name) VALUE ('Rottweiler');
INSERT INTO breed (name) VALUE ('Shih Tzu');
INSERT INTO breed (name) VALUE ('Siberian Husky');
INSERT INTO breed (name) VALUE ('Weimaraner');
INSERT INTO breed (name) VALUE ('Yorkshire Terrier');
